
export enum ActionsTypes {
  SET_SELECTED_LIVRE = "SET_SELECTED_LIVRE",
  REQUEST_LIVRES_LIST = "REQUEST_LIVRES_LIST",
  REQUEST_LIVRES_LIST_SUCCESS = "REQUEST_LIVRES_LIST_SUCCESS",
  REQUEST_LIVRES_LIST_ERROR = "REQUEST_LIVRES_LIST_ERROR",
   
}
 
